import type { NextPage } from "next";
import Head from "next/head";
import withAuth from "@/components/auth/with-auth";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>as</main>
    </div>
  );
};

export default withAuth(Home);
